version: '3.8'

services:
  client-api:
    build:
      context: /path/to/client-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - api-network

  commandes-api:
    build:
      context: /path/to/commandes-api
      dockerfile: Dockerfile
    ports:
      - "3001:8080"
    networks:
      - api-network

  produit-api:
    build:
      context: /path/to/produit-api
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
