name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    name: Build, Test, and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run Cucumber tests
        run: |
          # Replace this command with the command to run your Cucumber tests
          echo "Running Cucumber tests..."
          # For example:
          # dotnet test path/to/your/test/project

      # Add more steps for SonarQube analysis, code coverage, etc. if needed
